name: medtime_mobile
description: A new Flutter project.
publish_to: "none"
version: 1.1.0+28

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  # hive no sql database
  hive: ^2.2.3
  # path
  path_provider: ^2.1.2
  # equatable
  equatable: ^2.0.5
  # async
  async: ^2.11.0
  # cached image
  cached_network_image: ^3.3.1
  # freezed
  freezed_annotation: ^2.4.1
  # get it singleton
  get_it: ^7.6.7
  # bloc state manager
  flutter_bloc: ^8.1.4
  # interceptor
  dio: ^5.4.1
  dio_retry_plus: ^2.0.5
  # retrofit
  retrofit: ^4.1.0
  # chuck
  chuck_interceptor: ^2.0.9
  # box
  gap: ^3.0.1
  # pin put
  pinput: ^4.0.0
  # open file
  open_filex: ^4.4.0
  # firebase
  firebase_auth: ^4.17.3
  firebase_core: ^2.25.4
  firebase_analytics: ^10.8.6
  firebase_messaging: ^14.7.16
  firebase_remote_config: ^4.3.14
  # app metrica
  appmetrica_plugin: ^1.4.0
  # local notification
  flutter_local_notifications: ^16.3.2
  # svg
  flutter_svg: ^2.0.9
  # get files
  file_picker: ^6.1.1
  # open links
  url_launcher: ^6.2.4
  # photo zoom
  photo_view: ^0.14.0
  # http parse
  http_parser: ^4.0.2
  # shimmer effect
  shimmer: ^3.0.0
  # search text field
  flutter_typeahead: ^5.2.0
  # for read html text
  flutter_widget_from_html_core: ^0.14.11
  # app version
  package_info_plus: ^5.0.1
  # for permissions
  permission_handler: ^11.3.0
  # health for Apple Health and Google Fit
  health: ^10.2.0
  # google sign in
  google_sign_in: ^6.2.1
  # Redirect another app
  device_apps: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^8.1.0
  hive_generator: ^2.0.1
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  bloc_test: ^9.1.6
  freezed: ^2.4.7
  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true

  assets:
    - assets/locale/
    - assets/fonts/
    - assets/png/
    - assets/svg/
    - assets/logo/

  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf
